notifications:
  email: false

language: python

cache: pip

group: travis_latest

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.6
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.7   
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8        
      
install: pip install -e .  
          
script: python3 test/basetest.py